### ISSUE TITLE
AddUserRoleRequest required fields

### ISSUE THREAD

**Issue by haussli** [aristanetworks/ownership-voucher-grpc#12]
Are all fields of AddUserRoleRequest required?  Or, is org_id assumed from the hierarchy if omitted?

**Comment by harshitk-arista** [comment]
All of them are required. I think ownership delegation across different orgs was something we might have wanted to build. Unsure of what shape that might take in the service, the org id is thus left to be explicitly specified. It should be possible to get the behavior specified, but inferring org_id in the request = org_id of the calling user, if omitted.

**Comment by harshitk-arista** [comment]
INVALID_ARGuMENT is returned when any of teh fields are empty.

**Comment by haussli** [comment]
OK, https://github.com/aristanetworks/ownership-voucher-grpc/pull/16

And, yes, delegation across orgs is a necessary feature.
