### ISSUE TITLE
RemoveUserRole does not specify behavior if a group_id, org_id, or user_type are empty

### ISSUE THREAD

**Issue by haussli** [aristanetworks/ownership-voucher-grpc#13]
Is the org_id from the hierarchy assumed if empty?
If group_id is empty, is the username removed from all groups?  If yes, is  user_type matched?  if not, what is the point of user_type in RemoveUserRole?

**Comment by harshitk-arista** [comment]
INVALID_ARGuMENT is returned when any of the fields are empty.

`Is the org_id from the hierarchy assumed if empty?` org_id must be explicitly set and is not inferred right now.

`If yes, is user_type matched? if not, what is the point of user_type in RemoveUserRole?` user_type indicated the type of account - user account or service account. The tuple of <usernme,user_type,org_id> is what identified a caller and roles are accorded for each caller.

It is possible to have the same name for a user account and a service account. The user_type thus disambiguates the the caller (along with the org_id)

**Comment by haussli** [comment]
OK.  https://github.com/aristanetworks/ownership-voucher-grpc/pull/16 also updates the comments for this.

Also added a note about user uniqueness: https://github.com/aristanetworks/ownership-voucher-grpc/pull/17
