### ISSUE TITLE
GetUserRoleRequest missing group_id field?

### ISSUE THREAD

**Issue by haussli** [aristanetworks/ownership-voucher-grpc#14]
Also, I do not understand the usefulness of the user_type field in this request.

**Comment by harshitk-arista** [comment]
This method works across all groups.

`user_type field ` user name, user type and org id is what completely identifies a caller. It is possible, for a given org, to have accounts with the same name, but different user type - one of type user account and the other of type service account.

**Comment by haussli** [comment]
Sorry; confusing user_type and user_role again.
