### ISSUE TITLE
which PK? 

### ISSUE THREAD

**Issue by haussli** [aristanetworks/ownership-voucher-grpc#20]
Please be more specific in the comments about which PK is in GetOwnershipVoucherResponse.

https://github.com/aristanetworks/ownership-voucher-grpc/blob/main/ovgs.proto#L244

**Comment by harshitk-arista** [comment]
Added here - https://github.com/aristanetworks/ownership-voucher-grpc/commit/9290b68fe817c74278d65512c7d22b6cfb2f680d

**Comment by haussli** [comment]
ack;  thanks
