### ISSUE TITLE
AccountType needs more descriptive comments

### ISSUE THREAD

**Issue by haussli** [aristanetworks/ownership-voucher-grpc#6]
Please add comments describing these values in greater detail.  It is difficult to know what these mean without experience with CVaaS.

enum AccountType {
  ACCOUNT_TYPE_UNSPECIFIED = 0;
  ACCOUNT_TYPE_USER = 1;
  ACCOUNT_TYPE_SERVICE_ACCOUNT = 2;
}

**Comment by harshitk-arista** [comment]
Thanks for the issue. Will add some more details and push them out in a bit.

**Comment by harshitk-arista** [comment]
Added here - https://github.com/aristanetworks/ownership-voucher-grpc/commit/1858bfcda5db70bbe013af7643962d567f0ea632 which should make it a bit clearer.

**Comment by haussli** [comment]
Thanks
