### ISSUE TITLE
GetSerialResponse.public_key_der should be public cert

### ISSUE THREAD

**Issue by haussli** [aristanetworks/ownership-voucher-grpc#7]
I think that GetSerialResponse.public_key_der should be the certificate, obviously without the key, not the public key.  I think this was a temporary limitation.  How can both be accomodated for when that limitation is lifted?

**Comment by harshitk-arista** [comment]
`certificate` What certificate are you referring to here? This is the tpm's EK, as recorded by the device/components vendor.

This allows the bootstrap server to verify that the ek advertised by the device == the ek recorded by the device's vendor/manufacturing at manufacturing time (retrieved using this rpc) as a check in the attestation (and the overall bootstrapping) process. I

`public_key_der should be the certificate, obviously without the key, not the public key. I think this was a temporary limitation. How can both be accomodated for when that limitation is lifted?` Could you please elaborate on this?

**Comment by haussli** [comment]
Let me research; I might be confusing 1.2 and 2.0 - or just be confused.  My understanding is that this a certificate and that what you are currently providing is the pubkey extracted from the certificate.

**Comment by harshitk-arista** [comment]
Is there anything that's needed here?

**Comment by haussli** [comment]
Yeah...I need to do what I said I would ... research this.  Sorry.

**Comment by harshitk-arista** [comment]
Clarified here - https://github.com/aristanetworks/ownership-voucher-grpc/commit/9290b68fe817c74278d65512c7d22b6cfb2f680d

**Comment by haussli** [comment]
I agree with you Harshi.  Discussing with another vendor, but ...
Closing this and will take it to the oc repo, if necessary.  Thanks
